/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.EmpleadoDAO;
import Modelos.Empleados;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renea
 */
public class ListaEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form ListaEmpleados
     */
    public ListaEmpleados() {
        initComponents();
        setLocationRelativeTo(null);
        EmpleadoDAO dao = new EmpleadoDAO();
        List<Empleados> listadoEmpleados = dao.listar();
        System.out.println("CANTIDAD DE EMPLEADOS -> " + listadoEmpleados.size());

        tblEmpleados.setModel(new DefaultTableModel(
                new String[]{"RUT",
                    "NOMBRES",
                    "APELLIDO PATERNO",
                    "APELLIDO MATERNO",
                    "TELEFONO",
                    "TIPO EMPLEADO",}, listadoEmpleados.size()
        ));

        for (int i = 0; i < listadoEmpleados.size(); i++) {

            tblEmpleados.setValueAt(listadoEmpleados.get(i).getRut(), i, 0);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getNombres(), i, 1);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getApellidoPaterno(), i, 2);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getApellidoMaterno(), i, 3);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getTelefono(), i, 4);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getTipoEmpleado(), i, 5);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Listado de Empleados");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("RUT:");

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnVolver))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(36, 36, 36)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        MantenedorEmpleados empleados = new MantenedorEmpleados();
        empleados.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        EmpleadoDAO dao = new EmpleadoDAO();

        if ("".equals(txtRut.getText())) {
            List<Empleados> listadoEmpleados = dao.listar();
            System.out.println("CANTIDAD DE PERSONAS -> " + tblEmpleados.size());

        tblEmpleados.setModel(new DefaultTableModel(
                new String[]{"RUT",
                    "NOMBRES",
                    "APELLIDO PATERNO",
                    "APELLIDO MATERNO",
                    "TELEFONO",
                    "TIPO EMPLEADO",}, listadoEmpleados.size()
            ));

            for (int i = 0; i < listadoEmpleados.size(); i++) {

            tblEmpleados.setValueAt(listadoEmpleados.get(i).getRut(), i, 0);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getNombres(), i, 1);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getApellidoPaterno(), i, 2);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getApellidoMaterno(), i, 3);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getTelefono(), i, 4);
            tblEmpleados.setValueAt(listadoEmpleados.get(i).getTipoEmpleado(), i, 5);
            }
        } else {
            Empleados empl = dao.buscarPorRut(txtRut.getText());

        tblEmpleados.setModel(new DefaultTableModel(
                new String[]{"RUT",
                    "NOMBRES",
                    "APELLIDO PATERNO",
                    "APELLIDO MATERNO",
                    "TELEFONO",
                    "TIPO EMPLEADO",}, 1
            ));

            if (empl != null) {
                tblEmpleados.setValueAt(empl.getRut(), 0, 0);
                tblEmpleados.setValueAt(empl.getNombres(), 0, 1);
                tblEmpleados.setValueAt(empl.getApellidoPaterno(), 0, 2);
                tblEmpleados.setValueAt(empl.getApellidoMaterno(), 0, 3);
                tblEmpleados.setValueAt(empl.getTelefono(), 0, 4);
                tblEmpleados.setValueAt(empl.getTipoEmpleado(), 0, 5);
                
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
